package com.eswasthya.enums;

/**
 * Categorises the type of health alert generated by the system
 * when abnormal readings are detected.
 */
public enum AlertType {

    // BMI Alerts
    /** BMI below 18.5 — underweight risk */
    BMI_UNDERWEIGHT,

    /** BMI 25.0–29.9 — overweight range */
    BMI_OVERWEIGHT,

    /** BMI 30.0 or above — obesity range */
    BMI_OBESE,

    // Blood Pressure Alerts
    /** Systolic 130–139 or Diastolic 80–89 — Stage 1 Hypertension */
    HIGH_BP_STAGE1,

    /** Systolic ≥ 140 or Diastolic ≥ 90 — Stage 2 Hypertension */
    HIGH_BP_STAGE2,

    /** Systolic < 90 or Diastolic < 60 — Hypotension */
    LOW_BP,

    // Blood Glucose Alerts
    /** Fasting glucose < 70 mg/dL — Hypoglycaemia */
    LOW_GLUCOSE,

    /** Fasting glucose 100–125 mg/dL — Pre-diabetic range */
    GLUCOSE_PREDIABETIC,

    /** Fasting glucose ≥ 126 mg/dL — Diabetic range */
    GLUCOSE_DIABETIC,

    // Activity Level Alerts
    /** Self-reported LOW activity — sedentary lifestyle warning */
    SEDENTARY_LIFESTYLE
}
