# Docker profile. Environment variables should provide database credentials.
spring.web.cors.allowed-origins=http://localhost,http://localhost:80,http://127.0.0.1

logging.level.com.eswasthya=DEBUG
logging.level.org.springframework.security=INFO
